### ISSUE TITLE
Conflicts with and replaces nodejs-legacy but does not provide node

### ISSUE THREAD

**Issue by lloydhazlett** [dongjinleekr/graalvm-ce-deb#10]
The package lists ``nodejs-legacy`` as a [conflict](https://github.com/dongjinleekr/graalvm-ce-deb/blob/master/resources/control-template#L8) and replacement, but as far as I can tell it does not install ``/usr/bin/node``. The ``nodejs-legacy`` package "contains a symlink for legacy Node. js code requiring binary to be ``/usr/bin/node`` (not ``/usr/bin/nodejs`` as provided in Debian)".

The package description mentions providing both ``node`` and ``npm`` tools, but the produced package contents don't appear to contain binaries for either.

I'm wondering whether the ``Conflicts`` and ``Replaces`` lines should be removed from the control template so that nodesource nodejs packages which do provide ``nodejs``, ``npm`` and ``nodejs-legacy`` can still coexist with this package? I'm not sure why they were included or whether the package description mentioning it provides ``node`` and ``npm`` tools is accurate?

Edit: have just seen [Remove nodejs-legacy package from Conflicts field #9](https://github.com/dongjinleekr/graalvm-ce-deb/pull/9) about the same issue. Confirming the behaviour I had observed was building 22.1.0.

**Comment by dongjinleekr** [comment]
@lloydhazlett Thanks for reporting this issue. (Sorry for being late, I have been too busy for the weeks.)

I checked the release notes and found that [nodejs support is not enabled by default and must be installed explicitly from 21.1.0](https://www.graalvm.org/release-notes/21_1/#javascript). For some historical context, graalvm has been providing `nodejs`, and `npm` binaries - it is also why I specified the relationship between `nodejs-legacy` and `nodejs-doc` in package metadata. (Also, It should be `nodejs`, but I made a mistake specifying the package name.)

But now, only the `js` binary is built-in. So, `nodejs-legacy` should be removed from `Recommends`, `Conflicts`, and `Replaces`.

As a note, [the launchpad distribution](https://launchpad.net/graalvm-ce) provides `graal-node`, `graal-npm` and `graal-npx` and installs them as alternatives of `/usr/bin/node`, `/usr/bin/npm` and `/usr/bin/npx`, respectively. Its package metadata also refers the `nodejs-legacy` package but, will be removed soon.
