### ISSUE TITLE
Submit to Debian "non-free" archive

### ISSUE THREAD

**Issue by msgilligan** [dongjinleekr/graalvm-ce-deb#7]
I read the [Providing GraalVM Community Edition Debian package](https://www.mail-archive.com/debian-java@lists.debian.org/msg24908.html) discussion thread:

It seems the amount of work to make a Debian Free Software Guidelines compliant build of GraalVM is substantial.

As an interim solution, maybe you could put this package in the [non-free](https://www.debian.org/doc/debian-policy/ch-archive#s-non-free) archive area. That would still be useful to people in the Debian world and would create more demand for a DFSG-compliant version.

**Comment by msgilligan** [comment]
FYI: [Mandrel](https://github.com/graalvm/mandrel) is an interesting approach that would provide my use-case on Debian (native-image compiles of Java applications)

**Comment by msgilligan** [comment]
FYI: Upstream issue at https://github.com/oracle/graal - [Make GraalVM available in operating system package managers](https://github.com/oracle/graal/issues/3363)

**Comment by dongjinleekr** [comment]
Sorry for being late again. I tried to open a launchpad repo but, they accept buildable patches only, not pre-build packages.

So, I am now preparing for another package that does not embed the graalvm distribution; I greatly appreciate your attention, stay tuned!!

**Comment by dongjinleekr** [comment]
[Here](https://launchpad.net/graalvm-ce) it is. As of present, it supports java 11 based, amd64 only. However, the other packages will be added soon.
