### ISSUE TITLE
GraalVM 22.0.x version?

### ISSUE THREAD

**Issue by msgilligan** [dongjinleekr/graalvm-ce-deb#8]
Do you plan on creating an update for GraalVM 22.0.x?

**Comment by dongjinleekr** [comment]
Sorry for being late. I have been too busy with my new job; Fixed by 7bfdabe94ad2d38ac800d6344b97041d4dd4345b. ([Release 22.0.0.2-0](https://github.com/dongjinleekr/graalvm-ce-deb/releases/tag/22.0.0.2-0))
